### ISSUE TITLE
IndexError: invalid index

### ISSUE THREAD

**Issue by fzhcary** [quantopian/pyfolio#556]
hi
I am using pyfolio 0.9.0 and pandas 0.22

Got an error below(although the program continue running and plot graphs), does anyone have ideas?

Thanks a lot!

========
IndexErrorTraceback (most recent call last)
<ipython-input-16-ca2510cddaa6> in <module>()
----> 1 pf.create_returns_tear_sheet(stock_rets, benchmark_rets=benchmark_rets)

/home/frank/Envs/quants/local/lib/python2.7/site-packages/pyfolio/plotting.pyc in call_w_context(*args, **kwargs)
     50         if set_context:
     51             with plotting_context(), axes_style():
---> 52                 return func(*args, **kwargs)
     53         else:
     54             return func(*args, **kwargs)

/home/frank/Envs/quants/local/lib/python2.7/site-packages/pyfolio/tears.pyc in create_returns_tear_sheet(returns, positions, transactions, live_start_date, cone_std, benchmark_rets, bootstrap, turnover_denom, header_rows, return_fig)
    641     if ((bootstrap is not None)
    642             and (benchmark_rets is not None)):
--> 643         ax_bootstrap = plt.subplot(gs[i, :])
    644         plotting.plot_perf_stats(returns, benchmark_rets,
    645                                  ax=ax_bootstrap)

/home/frank/Envs/quants/local/lib/python2.7/site-packages/matplotlib/gridspec.pyc in __getitem__(self, key)
    159                 raise ValueError("unrecognized subplot spec")
    160             num1, num2 = np.ravel_multi_index(
--> 161                 [_normalize(k1, nrows), _normalize(k2, ncols)], (nrows, ncols))
    162         else:  # Single key
    163             num1, num2 = _normalize(key, nrows * ncols)

/home/frank/Envs/quants/local/lib/python2.7/site-packages/matplotlib/gridspec.pyc in _normalize(key, size)
    151                 if 0 <= key < size:
    152                     return key, key
--> 153             raise IndexError("invalid index")
    154 
    155         if isinstance(key, tuple):

IndexError: invalid index

**Comment by tdrobbin** [comment]
I'm also getting the same traceback with the same versions of pyfolio and pandas.

**Comment by twiecki** [comment]
Thanks for the report.

**Comment by twiecki** [comment]
This is a bit odd as that code shouldn't even get triggered. Can you try explicitly setting `bootstrap=False`?

**Comment by twiecki** [comment]
Also, can you try to uninstall and reinstall pyfolio?

**Comment by tdrobbin** [comment]
I tried passing ```bootstrap=False``` and reinstalling pyfolio, both to no avail.

Is there a specific github release I should try with pyfolio? Also, I'm using pip so not entirely sure about its internals, but it may be possible that I didn't actually download the latest version from pypi when i reinstalled, and perhaps just read from some already existing pip-cache from disk since they were both v0.9.0 (if such a thing exists?).

**Comment by tdrobbin** [comment]
Also, not sure if this is relevant or if I should start a separate issue, but when I pass ```benchmark_rets=None``` I get the following error

(For context in the traceback below) 
```python
backtest_df = zipline.api.run_algorithm(...)
bt['returns'], bt['positions'], bt['transactions'] = pf.utils.extract_rets_pos_txn_from_zipline(backtest_df)
```

then I call
```python
pf.create_full_tear_sheet(returns=bt['returns'].fillna(0), 
                          positions=bt['positions'], 
                          transactions=bt['transactions'],
                          benchmark_rets=None,
                          )
```

and get the below

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-105-bc96d8d60436> in <module>()
     11                           positions=bt['positions'],
     12                           transactions=bt['transactions'],
---> 13                           benchmark_rets=None,
     14                           )

~/anaconda/envs/sdactwo/lib/python3.6/site-packages/pyfolio/tears.py in create_full_tear_sheet(returns, positions, transactions, market_data, benchmark_rets, slippage, live_start_date, sector_mappings, bayesian, round_trips, estimate_intraday, hide_positions, cone_std, bootstrap, unadjusted_returns, style_factor_panel, sectors, caps, shares_held, volumes, percentile, turnover_denom, set_context, factor_returns, factor_loadings, pos_in_dollars, header_rows, factor_partitions)
    224     create_interesting_times_tear_sheet(returns,
    225                                         benchmark_rets=benchmark_rets,
--> 226                                         set_context=set_context)
    227 
    228     if positions is not None:

~/anaconda/envs/sdactwo/lib/python3.6/site-packages/pyfolio/plotting.py in call_w_context(*args, **kwargs)
     50         if set_context:
     51             with plotting_context(), axes_style():
---> 52                 return func(*args, **kwargs)
     53         else:
     54             return func(*args, **kwargs)

~/anaconda/envs/sdactwo/lib/python3.6/site-packages/pyfolio/tears.py in create_interesting_times_tear_sheet(returns, benchmark_rets, legend_loc, return_fig)
    985 
    986     bmark_interesting = timeseries.extract_interesting_date_ranges(
--> 987         benchmark_rets)
    988 
    989     num_plots = len(rets_interesting)

~/anaconda/envs/sdactwo/lib/python3.6/site-packages/pyfolio/timeseries.py in extract_interesting_date_ranges(returns)
   1220     """
   1221 
-> 1222     returns_dupe = returns.copy()
   1223     returns_dupe.index = returns_dupe.index.map(pd.Timestamp)
   1224     ranges = OrderedDict()

AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by johantilli** [comment]
Same error for me as well.

**Comment by johantilli** [comment]
Another interesting fact is that Pyfolio besides this error tells me two different annual returns. Se attached pictures.

##### Input:
pf.create_full_tear_sheet(my_returns, benchmark_rets=my_bmark)

##### Output:
Error Message:
IndexError                                Traceback (most recent call last)
<ipython-input-10-792bd4c790e0> in <module>()
----> 1 pf.create_full_tear_sheet(my_returns, benchmark_rets=my_bmark)

~\1\Anaconda3\lib\site-packages\pyfolio\tears.py in create_full_tear_sheet(returns, positions, transactions, market_data, benchmark_rets, slippage, live_start_date, sector_mappings, bayesian, round_trips, estimate_intraday, hide_positions, cone_std, bootstrap, unadjusted_returns, style_factor_panel, sectors, caps, shares_held, volumes, percentile, turnover_denom, set_context, factor_returns, factor_loadings, pos_in_dollars, header_rows, factor_partitions)
    220         turnover_denom=turnover_denom,
    221         header_rows=header_rows,
--> 222         set_context=set_context)
    223 
    224     create_interesting_times_tear_sheet(returns,

~\1\Anaconda3\lib\site-packages\pyfolio\plotting.py in call_w_context(*args, **kwargs)
     50         if set_context:
     51             with plotting_context(), axes_style():
---> 52                 return func(*args, **kwargs)
     53         else:
     54             return func(*args, **kwargs)

~\1\Anaconda3\lib\site-packages\pyfolio\tears.py in create_returns_tear_sheet(returns, positions, transactions, live_start_date, cone_std, benchmark_rets, bootstrap, turnover_denom, header_rows, return_fig)
    641     if ((bootstrap is not None)
    642             and (benchmark_rets is not None)):
--> 643         ax_bootstrap = plt.subplot(gs[i, :])
    644         plotting.plot_perf_stats(returns, benchmark_rets,
    645                                  ax=ax_bootstrap)

~\1\Anaconda3\lib\site-packages\matplotlib\gridspec.py in __getitem__(self, key)
    159                 raise ValueError("unrecognized subplot spec")
    160             num1, num2 = np.ravel_multi_index(
--> 161                 [_normalize(k1, nrows), _normalize(k2, ncols)], (nrows, ncols))
    162         else:  # Single key
    163             num1, num2 = _normalize(key, nrows * ncols)

~\1\Anaconda3\lib\site-packages\matplotlib\gridspec.py in _normalize(key, size)
    151                 if 0 <= key < size:
    152                     return key, key
--> 153             raise IndexError("invalid index")
    154 
    155         if isinstance(key, tuple):

IndexError: invalid index




![skarmbild 118](https://user-images.githubusercontent.com/40340894/44003295-c932b2a0-9e50-11e8-9f2c-12d86e970ac6.png)

![skarmbild 119](https://user-images.githubusercontent.com/40340894/44003296-c961e0ac-9e50-11e8-8a6f-a033883f8b1e.png)

**Comment by johantilli** [comment]
Also, the stress test part is missing from what is actually printed.

**Comment by arashgmn** [comment]
I had the same issue until I changed a line `tears.py` in my local. For some reason, I had `(bootstrap is not None)` at line 641. Changed the `None` to `False` and returns tears are working now. Although the current git source code has something else

https://github.com/quantopian/pyfolio/blob/77714d8b1b7d10228dbee80156a970ef2181386b/pyfolio/tears.py#L617

**Comment by johantilli** [comment]
Thanks for your reply @arashgmn!

Your answer lead me to look at the functions inside tears.py.

I changed function to "create_interesting_times_tear_sheet" and got what I wanted!

**Comment by twiecki** [comment]
I'm glad it's working but I really don't understand why your tears.py would look like that...

**Comment by twiecki** [comment]
Is this fixed with #568?

**Comment by sretlawd** [comment]
When I installed using pip (LATEST, 0.9.0) I had to do make the same change @arashgmn mentioned above.  Installing from git (0.8.0+190.g3568fec) works fine too.

**Comment by jainraje** [comment]
@twiecki 
I'm using pyfolio 0.9.0 and had to make the same change @arashgmn detailed above in tears.py line 641 to fix this error.

@fehiepsi if you merged something to fix this issue you may not have done it correctly. please check. i hope something else is not broken.

**Comment by fehiepsi** [comment]
@jainraje If I remember correctly, then I didn't fix this issue. I just fix the issue at the [comment](https://github.com/quantopian/pyfolio/issues/556#issuecomment-412255346).

**Comment by shintojoseph1234** [comment]
Just edit the local pyfolio library in your machine
`bmark_interesting = timeseries.extract_interesting_date_ranges(benchmark_rets)`

Indend the above code in line 986 and 987 under the if statement in line 983 in pyfolio/tears.py 
`if benchmark_rets is not None:`

This solved my issue. Thanks

**Comment by twiecki** [comment]
@shintojoseph1234 Thanks, can you try master which I think fixed this issue? If it works for you there we should just release a new version.

**Comment by shintojoseph1234** [comment]
@twiecki Issues #568 and #556 had already been fixed in the master. I think You can close this two open issues. Thanks

**Comment by twiecki** [comment]
Thanks @shintojoseph1234!
